import React from 'react';
import useStore from '../lib/store';
import DesktopWindow from '../components/DesktopWindow';
import SystemTelemetryChart from '../components/SystemTelemetryChart';
import CityMapWidget from '../components/CityMapWidget';
import KPICards from '../components/KPICards';
import AgentPanel from '../components/AgentPanel';
import SmsAlertWidget from '../components/SmsAlertWidget';
import ProphetCurveChart from '../components/ProphetCurveChart';
import FinancialBleedTracker from '../components/FinancialBleedTracker';
import CarbonOffsetWidget from '../components/CarbonOffsetWidget';
import { Cpu, Globe, Terminal as TerminalIcon, FileText } from 'lucide-react';
import jsPDF from 'jspdf';

const DashboardView = () => {
    const { networkData, setNetworkData } = useStore();

    const triggerManualAnomaly = () => {
        // Fallback nodes just in case the backend SSE hasn't loaded (common on Vercel)
        let baseNodes = networkData.nodes || [];

        if (baseNodes.length === 0) {
            // Generate dummy nodes if the store is empty
            for (let i = 0; i < 10; i++) {
                baseNodes.push({
                    id: `N${i}`,
                    status: 'nominal',
                    integrity_score: 98,
                    pressure: 45,
                    flow_rate: 20
                });
            }
        }

        const updatedNodes = baseNodes.map((n, i) => {
            // Force a massive leak on Node 1 (central Nagpur node)
            if (n.id === 'N1' || i === 1) {
                return {
                    ...n,
                    status: 'critical',
                    integrity_score: 12,
                    flow_rate: 84.8, // Massive flow burst
                    pressure: 24.5   // Massive pressure drop
                };
            }
            return n;
        });

        setNetworkData({
            ...networkData,
            nodes: updatedNodes,
            systemState: 'ANOMALOUS'
        });

        // Trigger dummy dispatch report too so the Admin panel lists it
        useStore.getState().setDispatchReport({
            id: 'T-9092',
            nodeId: 'N1',
            severity: 'CRITICAL',
            message: 'PHYSICAL BREACH DETECTED: TORRICELLI VARIANCE > 40%',
            timestamp: new Date().toISOString()
        });

        // Try the backend in background if it exists (for local demo)
        fetch('http://localhost:5000/api/trigger-anomaly', { method: 'POST' }).catch(() => { });
    };

    const generateExecutiveReport = () => {
        const doc = new jsPDF();
        doc.setFillColor(15, 23, 42); // slate-900 background
        doc.rect(0, 0, 210, 297, 'F');

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.setFont('helvetica', 'bold');
        doc.text("ALPHA SCRIPT - POST-INCIDENT MITIGATION", 20, 30);

        doc.setFontSize(12);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(148, 163, 184); // slate-400
        doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 40);

        doc.setDrawColor(30, 41, 59); // slate-800
        doc.line(20, 45, 190, 45);

        doc.setFontSize(14);
        doc.setTextColor(59, 130, 246); // blue-500
        doc.text("EXECUTIVE SUMMARY", 20, 60);

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(11);
        doc.text("The AI Autonomous Agent successfully mitigated a critical Level 4 fluid", 20, 70);
        doc.text("variance within the central transmission grid. Smart Dispatch protocol", 20, 77);
        doc.text("was engaged, re-routing flow to 3 adjacent macro-nodes in under 120ms.", 20, 84);

        doc.setTextColor(34, 211, 238); // cyan-400
        doc.text("FINANCIAL & ENVIRONMENTAL SAVINGS", 20, 105);

        doc.setTextColor(255, 255, 255);
        doc.text("• Total Water Saved: 142,000 Liters", 20, 115);
        doc.text("• Financial Capital Prevented from Bleeding: ₹28,50,000", 20, 122);
        doc.text("• Carbon Offset Earned vs Traditional Truck Roll: 15.4 kg CO2", 20, 129);
        doc.text("• Expected Uptime Maintained: 99.999%", 20, 136);

        doc.line(20, 145, 190, 145);
        doc.setTextColor(148, 163, 184); // slate-400
        doc.setFontSize(9);
        doc.text("CONFIDENTIAL - GENERATED BY ALPHA SCRIPT AI HYDROMATRIX", 20, 280);

        doc.save("AlphaScript_Executive_Report.pdf");
    };

    return (
        <div className="flex-1 h-full flex flex-col lg:flex-row gap-4 overflow-hidden">
            {/* Left Column: System Telemetry & SMS Alerts */}
            <div className="w-full lg:w-1/4 flex flex-col gap-4 h-full shrink-0">
                <DesktopWindow
                    title="Global_Telemetry_Matrix.exe"
                    headerRight={
                        <div className="flex items-center gap-2 text-[10px]">
                            <span className="flex items-center gap-1"><Cpu size={10} className="text-primary" /> 14%</span>
                            <span className="text-green-500">LIVE</span>
                        </div>
                    }
                    flex={3}
                >
                    <div className="relative flex-1 bg-black/20 overflow-hidden">
                        <div className="absolute inset-0">
                            <SystemTelemetryChart />
                        </div>
                    </div>
                </DesktopWindow>

                <DesktopWindow
                    title="Citizen_SMS_Broadcast.sys"
                    flex={2}
                >
                    <SmsAlertWidget />
                </DesktopWindow>
            </div>

            {/* Center Column: Core Visualization */}
            <div className="flex-1 flex flex-col gap-4 h-full min-w-0">
                <DesktopWindow
                    title="City_Grid_India.map"
                    headerRight={
                        <div className="flex items-center gap-1 text-primary">
                            <Globe size={12} /> SYNCED
                        </div>
                    }
                    flex={2}
                >
                    <div className="flex-1 relative bg-slate-900 overflow-hidden">
                        <CityMapWidget />
                    </div>
                </DesktopWindow>

                <DesktopWindow
                    title="Prophet_Demand_Forecast.ai"
                    flex={1}
                >
                    <ProphetCurveChart />
                </DesktopWindow>
            </div>

            {/* Right Column: Controls & Financial Metrics */}
            <div className="w-full lg:w-[28%] flex flex-col gap-4 h-full shrink-0">
                {/* Master Controls */}
                <div className="flex flex-col gap-2 shrink-0">
                    <button
                        onClick={generateExecutiveReport}
                        className="btn-premium w-full py-3 flex items-center justify-center gap-2 bg-slate-800 hover:bg-slate-700 text-cyan-400 font-bold text-[11px] uppercase cursor-pointer rounded border border-cyan-500/30"
                    >
                        <FileText size={14} /> One-Click Executive PDF Report
                    </button>
                    <button
                        onClick={triggerManualAnomaly}
                        className="btn-danger-glow animate-pulse-glow w-full px-4 py-3 flex items-center justify-center gap-2 group border border-red-500 rounded text-[11px]"
                    >
                        <div className="w-2 h-2 rounded-full bg-white animate-pulse"></div>
                        Trigger Torricelli Pipe Leak
                    </button>
                </div>

                <DesktopWindow title="Financial_Bleed.sys" flex={1}>
                    <FinancialBleedTracker />
                </DesktopWindow>

                <DesktopWindow
                    title="Live_Metrics_Console.bin"
                    headerRight={<div className="text-[10px] text-slate-500 uppercase">Buffer: 4.8MB</div>}
                    flex={2}
                >
                    <div className="flex-1 p-4 overflow-y-auto custom-scrollbar">
                        <KPICards />
                    </div>
                </DesktopWindow>
            </div>
        </div>
    );
};

export default DashboardView;
